config/routes.rb
PopHealth::Application.routes.draw do

  apipie

  devise_for :users, :controllers => {:registrations => "registrations"}

  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  put "admin/upload_patients"
  put "admin/upload_providers"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
  delete "admin/remove_providers"
  post 'api/measures/finalize'
  post 'api/measures/update_metadata'
  get "logs/index"
  post 'home/set_reporting_period'
  get "admin/user_profile"
  delete "admin/delete_user"
  post 'admin/set_user_practice'
  post 'admin/set_user_practice_provider'
  post "teams/:id/update", :to => 'teams#update'
  post "teams/create"
  post "teams/create_default" 
  get 'home/check_authorization'
  delete "practices/remove_patients"
  delete "practices/remove_providers"
   
  root :to => 'home#index'

  resources :practices 
  
  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end

    member do
      get :merge_list
      put :merge
    end
  end

  resources :teams

  namespace :api do
    get 'reports/qrda_cat3.xml', :to =>'reports#cat3', :format => :xml
    get 'reports/cat1/:id/:measure_ids', :to =>'reports#cat1', :format => :xml
    get 'teams/team_providers/:id', :to => 'teams#team_providers'
    get 'reports/patients', :to => 'reports#patients'
    get 'reports/measures_spreadsheet', :to =>'reports#measures_spreadsheet'
    get 'teams/team_providers/:id', :to => 'teams#team_providers'
    get 'reports/team_report', :to => 'reports#team_report'
    put 'admin/patient', :to => 'admin/patients#upload_single_patient'
    
    resources :practices
    resources :teams
    namespace :admin do
      resource :caches do
        collection do
          get :count
        end
      end
      resource :patients do
        collection do
          get :count
        end
      end
      resource :providers do
        collection do
          get :count
        end
      end
      resources :users do
        member do
          get :enable
          get :disable
          post :promote
          post :demote
          get :approve
          get :update_npi
        end
      end
    end
    resources :providers do
      resources :patients do
        collection do
          get :manage
          put :update_all
        end
      end
    end
    resources :patients do
      member do
        get :results
      end
    end

    resources :measures

    resources :queries do
       member do
        get :patients
        get :patient_results
        put :recalculate
       end
    end
  end

end

app/views/shared/_header.html.erb
<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header col-lg-4">
      <a class="logo"  href="/" style="max-width: initial"><%= image_tag "pophealth_logo_small-trans.png" %></a>
    </div>
    <div class="collapse navbar-collapse in">
      <ul class="nav navbar-nav pull-left" style="margin-top: 10px">
        <li class="location"><%# if Provider.root %><%#= Provider.root.given_name %><%# else %><%#= APP_CONFIG['practice_name'] %><%# end %>
          <%=
            if APP_CONFIG['use_opml_structure']
              if Provider.root
                Provider.root.given_name
              else
                APP_CONFIG['practice_name']
              end
            else
              current_user.practice ? current_user.practice.name : ''
            end
          %>
        </li>
      </ul>
       <ul class="nav pull-right">
        <li class="divider-vertical"></li>
        <li class="profile">
          <div class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="glyphicon glyphicon-user"></i>
              <%= current_user.first_name.to_s %>
            </a>
            <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="User">
              <% if APP_CONFIG['edit_account_enabled']%>
                <li><%=link_to raw('<i class="glyphicon glyphicon-edit"></i> Edit Account'), edit_user_registration_path(current_user) %></li>
              <% end %>
              <% if APP_CONFIG['logout_enabled']%>
                <li><%= link_to raw('<i class="glyphicon glyphicon-log-out"></i> Logout'), destroy_user_session_path, method: 'delete' %></li>
              <% end %>
              <% if current_user.staff_role? || current_user.admin? %>
                <li class="divider"></li>
                <li role="presentation" class="dropdown-header">Admin</li>
                <% if current_user.admin? && !APP_CONFIG['use_opml_structure']%> 
                  <li><%= link_to raw('<i class="glyphicon glyphicon-th-large"></i> Practices'), practices_path %></li> 
                <% end %>
                <li><%= link_to raw('<i class="glyphicon glyphicon-plus"></i> Providers'), '/#providers'%></li>
                <li><%= link_to raw('<i class="glyphicon glyphicon-list"></i> Manage Teams'), '/teams'%></li>
                <% if current_user.admin? %>
                  <% if (APP_CONFIG['patient_management_enabled']) %>
                    <li><%= link_to raw('<i class="glyphicon glyphicon-eye-open"></i> Patients'), admin_patients_path%></li>
                  <% end %>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-user"></i> Users'), admin_users_path%></li>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-list-alt"></i> Logs'), logs_index_path%></li>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-plus"></i> Measures'), '/#admin/measures'%></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </li>
        <li class="divider-vertical"></li>
      </ul>
    </div>
  </div>
</div>